name: Fake Test ci/cd pipeline

# 1. Define the triggering events
on:
  push:
    branches:
      - main
      - dev
    paths:
      - "02-ci-build-and-test/**"

jobs:
  # 2. Continuous Integration Job
  build-and-test:
    runs-on: ubuntu-latest

    # Default working directory for all run commands
    defaults:
      run:
        working-directory: 02-ci-build-and-test

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build Docker image
      - name: Build Docker Image
        run: docker build -t cicd-prod .

      # Step 3: Run Docker container
      - name: Run Container
        run: docker run -d -p 5000:5000 --name prod-container cicd-prod

      # Step 4: Wait for application to start
      - name: Wait for app
        run: sleep 5

      # Step 5: Run tests
      - name: Fake Test
        run: echo "All tests passed successfully"