name: CI Pipeline - Build & Test 0.2

on:
  push:      
    branches: 
      - main
      - dev
    paths:
      - "02-ci-build-and-test/**"

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run: 
        working-directory: 02-ci-build-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker
        run: docker build -t cicd-prod . 

     - name: Set API Key
        run: |
          echo "API_KEY=MY-SUPER-MY-Secret-Key" >> $GITHUB_ENV

      - name: Run Container
        run: |
          docker run -d \
            -p 5000:5000 \
            -e API_KEY="${{ env.API_KEY }}" \
            --name prod-container \
            cicd-prod

      - name: Wait for app(Fait if not ready)
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000; then
              echo "App is up!"
              exit 0
            fi 
            echo "Waiting for app..."
            sleep 2
          done

          echo "App Fsiled to start"
          exit 1
      
      - name: Real Health
        run: curl -f http://localhost:5000

      - name: cleanup container
        if: always()
        run: docker stop prod-container && docker rm prod-container

