name: CI/CD Pipeline

# 1. Define the triggering events
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 2. Continuous Integration Job (Runs on PRs and Pushes)
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name : List Files
      run : ls -la

    - name : echo massage
      run  : echo "pipeline is working"
