name: Basic CI Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout Code
        uses: actions/checkout@v4

      - name: List Files
        run: ls -la

      - name: Echo message
        run: echo "Pipeline is working"