name: Fake Test ci/cd pipeline

# 1. Define the triggering events
on:
  push:
    branches:
      - main
      - dev
    paths:
      - "02-ci-build-and-test/**"

jobs:
  # 2. Continuous Integration Job
  build-and-test:
    runs-on: ubuntu-latest

    # Default working directory for all run commands
    defaults:
      run:
        working-directory: 02-ci-build-and-test

    env:
      API_KEY:${{ secrets.API_KEY }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build Docker image
      - name: Build Docker Image
        run: docker build -t cicd-prod .

      # Step 3: Run Docker container
      - name: Run Container
        run: docker run -d -p 5000:5000 -e API_KEY=$API_KEY --name prod-container cicd-prod

      # Step 4: Wait for application to start
      - name: Wait for app (fail if not ready)
        run: 
          for i in {1..10};do
            if curl -s http://localhost:5000;then
              echo "App is up!"
              exit 0
              fi
              echo "waiting for app"
              sleep 2
            done

            echo "App failed to start"
            exit 1 

      # Step 5: Run tests
      - name: Check if app is running
        run: curl -f http://localhost:5000

      # clean container
      - name : Cleanup Container
        if : always()
        run : docker stop prod-container && docker rm prod-container